title: AVSS 2027
description: IEEE International Conference on Advanced Visual and Signal-Based Systems
url: "https://avss2027.org"
baseurl: ""
markdown: kramdown
plugins: []

defaults:
  - scope:
      path: ""
    values:
      layout: default
